apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-page
  namespace: landing-page
spec:
  ingressClassName: nginx
  rules:
    - host: newjoy.ro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-page
                port:
                  number: 80
    - host: www.newjoy.ro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-page
                port:
                  number: 80


