apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://authelia.authelia.svc.cluster.local/api/authz/forward-auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.newjoy.ro?rm=$request_method"
    nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Groups,Remote-Email,Remote-Name"
    # Forecastle dashboard
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/appName: "Longhorn"
    forecastle.stakater.com/group: "Storage"
    forecastle.stakater.com/icon: "https://longhorn.io/img/logos/longhorn-icon-white.png"
spec:
  ingressClassName: nginx
  rules:
    - host: longhorn.newjoy.ro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
