forecastle:
  config:
    namespaceSelector:
      any: true
    title: "newjoy.ro"
    instanceName: "homelab"

  service:
    expose: "true"

  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "http://authelia.authelia.svc.cluster.local/api/authz/forward-auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://auth.newjoy.ro/?rd=https://$http_host$request_uri"
      nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Groups,Remote-Email,Remote-Name"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
      nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header Accept "";
        proxy_set_header Cookie $http_cookie;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Uri $request_uri;
        proxy_set_header X-Forwarded-Method $request_method;
    hosts:
      - host: dashboard.newjoy.ro
        paths:
          - path: /
            pathType: Prefix
