forecastle:
  config:
    namespaceSelector:
      any: true
    title: "newjoy.ro"
    instanceName: "homelab"

  service:
    expose: "true"

  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "http://authelia.authelia.svc.cluster.local/api/authz/auth-request"
      nginx.ingress.kubernetes.io/auth-signin: "https://auth.newjoy.ro/?rd=https://$http_host$request_uri"
      nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Groups,Remote-Email,Remote-Name"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
      nginx.ingress.kubernetes.io/server-snippet: |
        set $pass_access_scheme_fixed https;
      nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Original-URL $pass_access_scheme_fixed://$http_host$request_uri;
    hosts:
      - host: dashboard.newjoy.ro
        paths:
          - path: /
            pathType: Prefix
