forecastle:
  config:
    namespaceSelector:
      any: true
    title: "newjoy.ro"
    instanceName: "homelab"

  service:
    expose: "true"

  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "http://authelia.authelia.svc.cluster.local/api/authz/forward-auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://auth.newjoy.ro?rm=$request_method"
      nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Groups,Remote-Email,Remote-Name"
    hosts:
      - host: dashboard.newjoy.ro
        paths:
          - path: /
            pathType: Prefix
