apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-queue-pvc
  namespace: mail-relay
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      # Small volume - just for queuing emails during outages
      storage: 256Mi

