apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: roundcube-db
  namespace: roundcube
  labels:
    app: roundcube
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2

  bootstrap:
    initdb:
      database: roundcube
      owner: roundcube

  storage:
    size: 1Gi
    storageClass: longhorn-ssd

  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 500m

