apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alpar-t/homelab
    targetRevision: main
    path: config/pihole
    directory:
      include: "ingress.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

